-- Generated by scripts/generate-categories-seed.mjs from
-- src/admin/data/categoriesData.ts's INITIAL_CATEGORIES — do not hand-edit,
-- re-run the generator instead so this never drifts from the real seed.
--
-- NOT auto-applied by `supabase db push`/`db reset`. Run manually
-- (Supabase SQL Editor or `psql -f`) as a deliberate step in the future
-- Categories migration phase — this file only exists to have that step
-- ready in advance.
insert into public.categories (id, name, description)
values
  ('cat-motherhood', '{"ar":"الأمومة والإلهام الإسلامي","en":"Motherhood & Islamic Inspiration"}'::jsonb, '{"ar":"كتب تجمع بين رحلة الأمومة والقيم الإيمانية.","en":"Books that bring together the journey of motherhood and faith-rooted values."}'::jsonb),
  ('cat-self-development', '{"ar":"التطوير الذاتي","en":"Self-Development"}'::jsonb, '{"ar":"أدوات وتأملات عملية لبناء نسخة أكثر ثباتًا من الذات.","en":"Practical tools and reflections for building a more grounded version of yourself."}'::jsonb),
  ('cat-spirituality', '{"ar":"الروحانيات","en":"Spirituality"}'::jsonb, '{"ar":"كتب تعيد الاتصال بالسكينة الداخلية والمعنى الإيماني.","en":"Books that reconnect you with inner tranquility and spiritual meaning."}'::jsonb),
  ('cat-literature', '{"ar":"الأدب والسيرة","en":"Literature & Biography"}'::jsonb, '{"ar":"سرد أدبي وسير ملهمة بلمسة معاصرة.","en":"Literary narrative and inspiring biographies with a contemporary touch."}'::jsonb),
  ('cat-parenting', '{"ar":"تربية الأبناء","en":"Parenting"}'::jsonb, '{"ar":"محتوى يرافق الأمهات في رحلة تربية أبنائهن.","en":"Content that accompanies mothers on their journey of raising their children."}'::jsonb)
on conflict (id) do nothing;
