-- Generated by scripts/generate-coupons-seed.mjs from
-- src/admin/data/couponsData.ts's INITIAL_COUPONS — do not hand-edit,
-- re-run the generator instead so this never drifts.
--
-- NOT auto-applied by `supabase db push`/`db reset`. Run manually
-- (Supabase SQL Editor or `psql -f`) as a deliberate step in the Coupons
-- migration, only after the repository has been verified independently.
insert into public.coupons (id, code, type, value, min_order_value, usage_limit, usage_count, starts_at, expires_at, enabled, description)
values
  ('cp-welcome10', 'WELCOME10', 'percentage', 10, null, null, 0, null, null, false, 'خصم ترحيبي لأول عملية شراء.'),
  ('cp-hajar20', 'HAJAR20', 'percentage', 20, null, null, 0, null, null, false, 'خصم مناسبة خاصة بإصدار كوني هاجر.'),
  ('cp-firstorder', 'FIRSTORDER', 'fixed', 3, null, null, 0, null, null, false, 'خصم ثابت لأول طلب لعميلة جديدة.'),
  ('cp-ramadan', 'RAMADAN', 'percentage', 15, null, null, 0, null, null, false, 'خصم موسمي لشهر رمضان.'),
  ('cp-vip30', 'VIP30', 'percentage', 30, null, 50, 0, null, null, false, 'خصم كبير للعميلات المميزات — عدد محدود من الاستخدامات.')
on conflict (id) do nothing;
