-- Generated by scripts/generate-media-seed.mjs from
-- src/admin/data/mediaData.ts's INITIAL_MEDIA_FOLDERS/INITIAL_MEDIA_ASSETS —
-- do not hand-edit, re-run the generator instead so this never drifts.
--
-- NOT auto-applied by `supabase db push`/`db reset`. Run manually
-- (Supabase SQL Editor or `psql -f`) as a deliberate step in the Media
-- migration, only after the repository has been verified independently.
-- Folders first -- media_assets.folder_id references media_folders.id.
insert into public.media_folders (id, name)
values
  ('folder-covers', 'أغلفة الكتب'),
  ('folder-marketing', 'صور تسويقية'),
  ('folder-brand', 'الهوية البصرية')
on conflict (id) do nothing;

insert into public.media_assets (id, storage_key, url, name, type, folder_id, size, width, height)
values
  ('media-cover-front', '/books/kuni-hajar/cover.webp', '/books/kuni-hajar/cover.webp', 'كوني هاجر — الغلاف الأمامي', 'image', 'folder-covers', 812000, 1000, 1400),
  ('media-cover-back', '/books/kuni-hajar/back.webp', '/books/kuni-hajar/back.webp', 'كوني هاجر — الغلاف الخلفي', 'image', 'folder-covers', 745000, 1000, 1400),
  ('media-page-01', '/books/kuni-hajar/page-01.webp', '/books/kuni-hajar/page-01.webp', 'كوني هاجر — معاينة صفحة ١', 'image', 'folder-covers', 640000, 1000, 1400),
  ('media-page-02', '/books/kuni-hajar/page-02.webp', '/books/kuni-hajar/page-02.webp', 'كوني هاجر — معاينة صفحة ٢', 'image', 'folder-covers', 655000, 1000, 1400),
  ('media-page-03', '/books/kuni-hajar/page-03.webp', '/books/kuni-hajar/page-03.webp', 'كوني هاجر — معاينة صفحة ٣', 'image', 'folder-covers', 661000, 1000, 1400),
  ('media-page-04', '/books/kuni-hajar/page-04.webp', '/books/kuni-hajar/page-04.webp', 'كوني هاجر — معاينة صفحة ٤', 'image', 'folder-covers', 648000, 1000, 1400),
  ('media-page-05', '/books/kuni-hajar/page-05.webp', '/books/kuni-hajar/page-05.webp', 'كوني هاجر — معاينة صفحة ٥', 'image', 'folder-covers', 652000, 1000, 1400),
  ('media-collection', '/assets/kuni-hajar-collection.webp', '/assets/kuni-hajar-collection.webp', 'مجموعة كوني هاجر التسويقية', 'image', 'folder-marketing', 1240000, 1600, 1200),
  ('media-book-cutout', '/assets/book-cutout.webp', '/assets/book-cutout.webp', 'قصاصة الكتاب الفنية', 'image', 'folder-marketing', 980000, 1400, 1400),
  ('media-book-detail', '/assets/book-kuni-hajar-detail.webp', '/assets/book-kuni-hajar-detail.webp', 'تفاصيل غلاف كوني هاجر', 'image', 'folder-marketing', 890000, 1400, 1050),
  ('media-book-linen', '/assets/book-linen.webp', '/assets/book-linen.webp', 'نسيج الكتاب', 'image', 'folder-marketing', 760000, 1400, 1050),
  ('media-books-grid', '/assets/books-grid.webp', '/assets/books-grid.webp', 'شبكة عرض الكتب', 'image', 'folder-marketing', 1050000, 1600, 1000),
  ('media-coming-soon-01', '/assets/lumora-coming-soon-01.webp', '/assets/lumora-coming-soon-01.webp', 'إصدار قادم — معاينة ١', 'image', 'folder-marketing', 705000, 1200, 1500),
  ('media-coming-soon-02', '/assets/lumora-coming-soon-02.webp', '/assets/lumora-coming-soon-02.webp', 'إصدار قادم — معاينة ٢', 'image', 'folder-marketing', 712000, 1200, 1500),
  ('media-coming-soon-03', '/assets/lumora-coming-soon-03.webp', '/assets/lumora-coming-soon-03.webp', 'إصدار قادم — معاينة ٣', 'image', 'folder-marketing', 698000, 1200, 1500),
  ('media-logo', '/Raqim-logo.webp', '/Raqim-logo.webp', 'شعار رقيم', 'image', 'folder-brand', 146572, 1024, 1536),
  ('media-favicon', '/favicon.ico', '/favicon.ico', 'أيقونة الموقع (Favicon)', 'image', 'folder-brand', 735, 32, 32),
  ('media-house', '/assets/Lumora House.webp', '/assets/Lumora House.webp', 'صورة رقيم الرئيسية', 'image', 'folder-brand', 980000, 1600, 1000),
  ('media-arabesque', '/assets/arabesque-pattern.webp', '/assets/arabesque-pattern.webp', 'النقش العربي (زخرفة)', 'image', 'folder-brand', 420000, 1200, 1200),
  ('media-philosophy', '/assets/philosophy.webp', '/assets/philosophy.webp', 'صورة الفلسفة', 'image', 'folder-brand', 890000, 1400, 1750),
  ('media-about', '/assets/lumora-about.webp', '/assets/lumora-about.webp', 'صورة عن الدار', 'image', 'folder-brand', 910000, 1400, 1400),
  ('media-og', '/og-image.webp', '/og-image.webp', 'صورة المشاركة الاجتماعية', 'image', 'folder-brand', 198772, 1730, 909)
on conflict (id) do nothing;
