// Paths of every journey image and video, served statically from
// public/journey/. To swap a file, change its path here.
// v4–v8 are the upscaled clips (1728×992), used on screens ≥ 900px wide only:
// phones show the sharp stills instead (see MOBILE in engine.ts).
const IMG = "/journey/img";
const VID = "/journey/video";

export const A: Record<string, string> = {
  "01A": `${IMG}/bg/01A.webp`,
  "01B": `${IMG}/bg/01B.webp`,
  "09A": `${IMG}/bg/09A.webp`,
  "09B": `${IMG}/bg/09B.webp`,
  "10A": `${IMG}/bg/10A.webp`,
  "10B": `${IMG}/bg/10B.webp`,
  "11A": `${IMG}/bg/11A.webp`,
  "11B": `${IMG}/bg/11B.webp`,
  "12A": `${IMG}/bg/12A.webp`,
  "12B": `${IMG}/bg/12B.webp`,
  "13A": `${IMG}/bg/13A.webp`,
  "13B": `${IMG}/bg/13B.webp`,
  "15A": `${IMG}/bg/15A.webp`,
  "15B": `${IMG}/bg/15B.webp`,
  "peak-A": `${IMG}/summit/peak-A.webp`,
  "peak-B": `${IMG}/summit/peak-B.webp`,
  rock1: `${IMG}/summit/rock1.webp`,
  rock2: `${IMG}/summit/rock2.webp`,
  rock3: `${IMG}/summit/rock3.webp`,
  rock4: `${IMG}/summit/rock4.webp`,
  "book-05": `${IMG}/summit/book-05.webp`,
  "book-06": `${IMG}/summit/book-06.webp`,
  "book-06b": `${IMG}/summit/book-06b.webp`,
  "book-07": `${IMG}/summit/book-07.webp`,
  page1: `${IMG}/pages/page1.webp`,
  page2: `${IMG}/pages/page2.webp`,
  page3: `${IMG}/pages/page3.webp`,
  page4: `${IMG}/pages/page4.webp`,
  page5: `${IMG}/pages/page5.webp`,
  page6: `${IMG}/pages/page6.webp`,
  fly1: `${IMG}/books/fly1.webp`,
  fly2: `${IMG}/books/fly2.webp`,
  fly3: `${IMG}/books/fly3.webp`,
  fly4: `${IMG}/books/fly4.webp`,
  fly5: `${IMG}/books/fly5.webp`,
  fly6: `${IMG}/books/fly6.webp`,
  fly7: `${IMG}/books/fly7.webp`,
  fly8: `${IMG}/books/fly8.webp`,
  fly9: `${IMG}/books/fly9.webp`,
  spine1: "/journey/ui/spine1.webp",
  spine2: "/journey/ui/spine2.webp",
  spine3: "/journey/ui/spine3.webp",
  spine4: "/journey/ui/spine4.webp",
  spine5: "/journey/ui/spine5.webp",
  spine6: "/journey/ui/spine6.webp",
  // quill cursor, 64×96 and its 2× version (nib tip at the bottom-left)
  feather: "/journey/ui/feather-cursor.webp",
  feather2x: "/journey/ui/feather-cursor@2x.webp",
  v1: `${VID}/web/v1.mp4`,
  v2: `${VID}/web/v2.mp4`,
  v3: `${VID}/web/v3.mp4`,
  v4: `${VID}/web/v4.mp4`,
  v5: `${VID}/web/v5.mp4`,
  v6: `${VID}/web/v6.mp4`,
  v7: `${VID}/web/v7.mp4`,
  v8: `${VID}/web/v8.mp4`,
};
